### PR TITLE
Allow Changing Files Order

### LINKED ISSUE #38: Arrange Files Order according to the books in the Bible

### PR DESCRIPTION
**Pull request by AnonymousWalker**

### CODE REVIEW

**Comment by rbnswartz** [comment]
We shouldn't be allowing people to change the order of these scripture files. The better way to do this is to look at the metadata of the USFM files and then set the order in that way.

**Review by rbnswartz — CHANGES_REQUESTED** [review]
We shouldn't be allowing people to change the order of these scripture files. The better way to do this is to look at the metadata of the USFM files and then set the order in that way.

**Comment by AnonymousWalker** [comment]
> We shouldn't be allowing people to change the order of these scripture files. The better way to do this is to look at the metadata of the USFM files and then set the order in that way.

@rbnswartz this request comes from our product owner (#48). I don't have a strong opinion to that. There could be the case when usfm files are added separately, which could have incorrect order.

**Comment by PurpleGuitar** [comment]
It looks like you implemented this using a set of up/down buttons.  Would it be possible to implement drag-and-drop, where the user can change the order of columns just by clicking them and moving the mouse?

**Comment by AnonymousWalker** [comment]
> It looks like you implemented this using a set of up/down buttons. Would it be possible to implement drag-and-drop, where the user can change the order of columns just by clicking them and moving the mouse?

@PurpleGuitar, @Thundelly and I did a spike on that (drag and drop ~ similar) for a couple hours and didn't have any outcome at all. There seemed to have some limitation in retrieving pointer position from the mouse drag event and similar things in the framework.
I think we can temporarily have the up/down buttons that way and let's see whether there is a need to invest more time on it or not.

**Pull request closed without merging**
